services:
  shopify-app-auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopify-app-auth
    ports:
      - "9998:9998"
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    restart: unless-stopped
